export enum WidgetType {
  TECH_STACK = 'TECH_STACK',
  POST_IT = 'POST_IT',
  GROUND_RULE = 'GROUND_RULE',
  GIT_CONVENTION = 'GIT_CONVENTION',
  COLLABORATION = 'COLLABORATION',
  COMMUNICATION = 'COMMUNICATION',
  NAMING_CONVENTION = 'NAMING_CONVENTION',
}
