import { Test, TestingModule } from '@nestjs/testing';

import { MarkdownService } from '../markdown.service';
import { YjsDocReaderService } from '../../collaboration/yjs-doc-reader.service';

describe('MarkdownService', () => {
  let service: MarkdownService;
  let yjsDocReaderMock: { getWidgets: jest.Mock };
  const workspaceId = 'w1';

  beforeEach(async () => {
    yjsDocReaderMock = {
      getWidgets: jest.fn(),
    };

    const module: TestingModule = await Test.createTestingModule({
      providers: [
        MarkdownService,
        {
          provide: YjsDocReaderService,
          useValue: yjsDocReaderMock,
        },
      ],
    }).compile();

    service = module.get<MarkdownService>(MarkdownService);
    jest.useFakeTimers().setSystemTime(new Date('2024-01-01T12:00:00Z'));
  });

  afterEach(() => {
    jest.useRealTimers();
  });

  it('모든 위젯이 없으면 헤더, 푸터, 안내 문구를 반환한다.', () => {
    yjsDocReaderMock.getWidgets.mockReturnValue([]);

    const markdown = service.generateMarkdown(workspaceId);

    expect(markdown).toContain(
      '아직 적은 내용이 없는 것 같습니다! 위젯에 내용을 추가해보세요! 🚀',
    );
    expect(markdown).toContain('*Generated by TeamConfig*');
  });
});
