import { Test, TestingModule } from '@nestjs/testing';

import { MarkdownService } from '../markdown.service';
import { IWidgetService, WIDGET_SERVICE } from '../../widget/widget.interface';

type MockWidgetService = {
  [P in keyof IWidgetService]: jest.Mock;
};

describe('MarkdownService', () => {
  let service: MarkdownService;
  let widgetServiceMock: MockWidgetService;
  const workspaceId = 'w1';

  beforeEach(async () => {
    widgetServiceMock = {
      create: jest.fn(),
      findAll: jest.fn(),
      findOne: jest.fn(),
      lock: jest.fn(),
      unlock: jest.fn(),
      getLockOwner: jest.fn(),
      unlockAllByUser: jest.fn(),
      update: jest.fn(),
      remove: jest.fn(),
      updateLayout: jest.fn(),
    };

    const module: TestingModule = await Test.createTestingModule({
      providers: [
        MarkdownService,
        {
          provide: WIDGET_SERVICE,
          useValue: widgetServiceMock,
        },
      ],
    }).compile();

    service = module.get<MarkdownService>(MarkdownService);
    jest.useFakeTimers().setSystemTime(new Date('2024-01-01T12:00:00Z'));
  });

  afterEach(() => {
    jest.useRealTimers();
  });

  it('모든 위젯이 없으면 헤더, 푸터, 안내 문구를 반환한다.', async () => {
    widgetServiceMock.findAll.mockResolvedValue([]);

    const markdown = await service.generateMarkdown(workspaceId);

    expect(markdown).toContain(
      '아직 적은 내용이 없는 것 같습니다! 위젯에 내용을 추가해보세요! 🚀',
    );
    expect(markdown).toContain('*Generated by TeamConfig*');
  });
});
