import { Test, TestingModule } from '@nestjs/testing';

import { MarkdownService } from '../markdown.service';
import { YjsDocReaderService } from '../../collaboration/yjs-doc-reader.service';
import type { YjsWidgetData } from '../../collaboration/types/yjs-widget.types';

describe('MarkdownService', () => {
  let service: MarkdownService;
  let yjsDocReaderMock: { getWidgets: jest.Mock };
  const workspaceId = 'w1';

  beforeEach(async () => {
    yjsDocReaderMock = {
      getWidgets: jest.fn(),
    };

    const module: TestingModule = await Test.createTestingModule({
      providers: [
        MarkdownService,
        {
          provide: YjsDocReaderService,
          useValue: yjsDocReaderMock,
        },
      ],
    }).compile();

    service = module.get<MarkdownService>(MarkdownService);
    jest.useFakeTimers().setSystemTime(new Date('2024-01-01T12:00:00Z'));
  });

  afterEach(() => {
    jest.useRealTimers();
  });

  it('모든 위젯이 없으면 헤더, 푸터, 안내 문구를 반환한다.', () => {
    yjsDocReaderMock.getWidgets.mockReturnValue([]);

    const markdown = service.generateMarkdown(workspaceId);

    expect(markdown).toContain('### 🚀 아직 작성된 내용이 없습니다.');
    expect(markdown).toContain('위젯을 추가하여 팀의 규칙을 정의해보세요!');
    expect(markdown).toContain('*Generated by TeamConfig*');
  });

  it('COLLABORATION 위젯이 있으면 협업 규칙 마크다운을 생성한다.', () => {
    const collaborationWidget: YjsWidgetData = {
      widgetId: 'collab-1',
      type: 'COLLABORATION',
      layout: { x: 0, y: 0, width: 300, height: 300 },
      createdAt: Date.now(),
      content: {
        prRules: {
          activeVersion: {
            selectedId: 'v1',
            options: { v1: { value: 'Semantic Versioning', createdAt: 0 } },
          },
          activeStrategy: {
            selectedId: 's1',
            options: { s1: { value: 'Squash and Merge', createdAt: 0 } },
          },
          labelRules: {
            selectedIds: ['l1', 'l2'],
            options: {
              l1: { value: 'bug', createdAt: 0 },
              l2: { value: 'feature', createdAt: 0 },
            },
          },
        },
        reviewPolicy: {
          approves: 2,
          maxReviewHours: 24,
          blockMerge: true,
        },
        workflow: {
          platform: {
            selectedId: 'p1',
            options: { p1: { value: 'GitHub Projects', createdAt: 0 } },
          },
          cycleValue: 2,
          cycleUnit: '주',
        },
      } as Record<string, unknown>,
    };

    yjsDocReaderMock.getWidgets.mockReturnValue([collaborationWidget]);

    const markdown = service.generateMarkdown(workspaceId);

    expect(markdown).toContain('## 🤝 협업 규칙');
    expect(markdown).toContain('### 🔀 Pull Request 규칙');
    expect(markdown).toContain('Semantic Versioning');
    expect(markdown).toContain('Squash and Merge');
    expect(markdown).toContain('`bug`, `feature`');
    expect(markdown).toContain('### 🧐 리뷰 정책 (Review Policy)');
    expect(markdown).toContain('🛡️ **2명**');
    expect(markdown).toContain('⏰ **24h**');
    expect(markdown).toContain('🔴 **YES**');
    expect(markdown).toContain('### 🔄 워크플로우 (Workflow)');
    expect(markdown).toContain('GitHub Projects');
    expect(markdown).toContain('2주');
  });

  it('COMMUNICATION 위젯이 있으면 커뮤니케이션 마크다운을 생성한다.', () => {
    const communicationWidget: YjsWidgetData = {
      widgetId: 'comm-1',
      type: 'COMMUNICATION',
      layout: { x: 0, y: 0, width: 300, height: 300 },
      createdAt: Date.now(),
      content: {
        communication: {
          urgent: {
            selectedId: 'u1',
            options: { u1: { value: '전화', createdAt: 0 } },
          },
          sync: {
            selectedId: 's1',
            options: { s1: { value: 'Zoom', createdAt: 0 } },
          },
          async: {
            selectedId: 'a1',
            options: { a1: { value: 'Slack', createdAt: 0 } },
          },
          official: {
            selectedId: 'o1',
            options: { o1: { value: '이메일', createdAt: 0 } },
          },
        },
        sla: {
          responseTime: 24,
        },
        timeManagement: {
          coreTimeStart: '10:00',
          coreTimeEnd: '18:00',
        },
        meeting: {
          noMeetingDay: '수요일',
          feedbackStyle: '직접적',
        },
      } as Record<string, unknown>,
    };

    yjsDocReaderMock.getWidgets.mockReturnValue([communicationWidget]);

    const markdown = service.generateMarkdown(workspaceId);

    expect(markdown).toContain('## 💬 커뮤니케이션');
    expect(markdown).toContain('### 📢 채널 가이드');
    expect(markdown).toContain('전화');
    expect(markdown).toContain('Zoom');
    expect(markdown).toContain('Slack');
    expect(markdown).toContain('이메일');
    expect(markdown).toContain('### ⏳ 시간 관리 및 미팅');
    expect(markdown).toContain('코어 타임 (Core Time)');
    expect(markdown).toContain('`10:00` ~ `18:00`');
    expect(markdown).toContain('최대 응답 시간 (SLA)');
    expect(markdown).toContain('24h');
    expect(markdown).toContain('미팅 없는 날');
    expect(markdown).toContain('수요일');
    expect(markdown).toContain('피드백 스타일');
    expect(markdown).toContain('직접적');
  });

  it('TECH_STACK 위젯이 있으면 기술 스택 마크다운을 생성한다.', () => {
    const techStackWidget: YjsWidgetData = {
      widgetId: 'tech-1',
      type: 'TECH_STACK',
      layout: { x: 0, y: 0, width: 300, height: 300 },
      createdAt: Date.now(),
      content: {
        subject: {
          selectedId: 's1',
          options: { s1: { value: 'Frontend', createdAt: 0 } },
        },
        techItems: [
          { id: 't1', name: 'React', category: 'Library' },
          { id: 't2', name: 'TypeScript', category: 'Language' },
        ],
      } as Record<string, unknown>,
    };

    yjsDocReaderMock.getWidgets.mockReturnValue([techStackWidget]);

    const markdown = service.generateMarkdown(workspaceId);

    expect(markdown).toContain('## 🛠 기술 스택');
    expect(markdown).toContain('### Frontend');
    expect(markdown).toContain('React');
    expect(markdown).toContain('TypeScript');
  });

  it('GIT_CONVENTION 위젯이 있으면 그라운드 룰 마크다운을 생성한다.', () => {
    const gitConventionWidget: YjsWidgetData = {
      widgetId: 'git-1',
      type: 'GIT_CONVENTION',
      layout: { x: 0, y: 0, width: 300, height: 300 },
      createdAt: Date.now(),
      content: {
        strategy: {
          selectedId: 's1',
          options: { s1: { value: 'GITHUB_FLOW', createdAt: 0 } },
        },
        branchRules: {
          mainBranch: 'main',
          developBranch: 'develop',
          prefixes: {
            selectedIds: ['p1', 'p2'],
            options: {
              p1: { value: 'feat', createdAt: 0 },
              p2: { value: 'fix', createdAt: 0 },
            },
          },
        },
        commitConvention: {
          commitTypes: {
            selectedIds: ['c1'],
            options: { c1: { value: 'chore', createdAt: 0 } },
          },
        },
      } as Record<string, unknown>,
    };

    yjsDocReaderMock.getWidgets.mockReturnValue([gitConventionWidget]);

    const markdown = service.generateMarkdown(workspaceId);

    expect(markdown).toContain('## 🐙 Git 컨벤션');
    expect(markdown).toContain('### 🧩 브랜치 전략');
    expect(markdown).toContain('GitHub Flow');
    expect(markdown).toContain('### 🌿 브랜치 규칙');
    expect(markdown).toContain('main');
    expect(markdown).toContain('develop');
    expect(markdown).toContain('`feat`, `fix`');
    expect(markdown).toContain('### 📝 커밋 컨벤션');
    expect(markdown).toContain('chore');
  });

  it('POST_IT 위젯이 있으면 해당 내용을 포함한다.', () => {
    const postItWidget: YjsWidgetData = {
      widgetId: 'post-1',
      type: 'POST_IT',
      layout: { x: 0, y: 0, width: 300, height: 300 },
      createdAt: Date.now(),
      content: {
        text: '중요한 메모입니다.',
      } as Record<string, unknown>,
    };

    yjsDocReaderMock.getWidgets.mockReturnValue([postItWidget]);

    const markdown = service.generateMarkdown(workspaceId);

    expect(markdown).toContain('## 📌 그 외');
    expect(markdown).toContain('중요한 메모입니다.');
  });

  it('NAMING_CONVENTION 위젯이 있으면 네이밍 컨벤션 마크다운을 생성한다.', () => {
    const namingConventionWidget: YjsWidgetData = {
      widgetId: 'naming-1',
      type: 'NAMING_CONVENTION',
      layout: { x: 0, y: 0, width: 300, height: 300 },
      createdAt: Date.now(),
      content: {
        frontend: {
          variable: 'camelCase',
          function: 'camelCase',
          component: 'PascalCase',
          constant: 'UPPER_SNAKE_CASE',
        },
        backend: {
          variable: 'camelCase',
          function: 'camelCase',
          class: 'PascalCase',
          constant: 'UPPER_SNAKE_CASE',
        },
        database: {
          table: 'snake_case',
          column: 'snake_case',
          index: 'idx_prefix',
          constraint: 'pk_prefix',
        },
        common: {
          utility: 'camelCase',
          constant: 'UPPER_SNAKE_CASE',
          type: 'PascalCase',
          enum: 'UPPER_SNAKE_CASE',
        },
      } as Record<string, unknown>,
    };

    yjsDocReaderMock.getWidgets.mockReturnValue([namingConventionWidget]);

    const markdown = service.generateMarkdown(workspaceId);

    expect(markdown).toContain('## 📝 네이밍 컨벤션');
    expect(markdown).toContain('### Frontend');
    expect(markdown).toContain('camelCase');
    expect(markdown).toContain('PascalCase');
    expect(markdown).toContain('### Backend');
    expect(markdown).toContain('### Database');
    expect(markdown).toContain('snake_case');
    expect(markdown).toContain('### Common');
    expect(markdown).toContain('열거형');
  });

  it('FORMAT 위젯이 있으면 코드 포맷 마크다운을 생성한다.', () => {
    const formatWidget: YjsWidgetData = {
      widgetId: 'format-1',
      type: 'FORMAT',
      layout: { x: 0, y: 0, width: 300, height: 300 },
      createdAt: Date.now(),
      content: {
        line: 80,
        useTabs: false,
        tabWidth: 2,
        semi: true,
        singleQuote: true,
        jsxSingleQuote: false,
        bracketSpacing: true,
        trailingComma: 'all',
        arrowParens: true,
        attributePerLine: true,
      } as Record<string, unknown>,
    };

    yjsDocReaderMock.getWidgets.mockReturnValue([formatWidget]);

    const markdown = service.generateMarkdown(workspaceId);

    expect(markdown).toContain('## ⚙️ 코드 포맷 (Code Format)');
    expect(markdown).toContain('줄 길이');
    expect(markdown).toContain('80');
    expect(markdown).toContain('탭 사용');
    expect(markdown).toContain('들여쓰기 폭');
    expect(markdown).toContain('세미콜론');
    expect(markdown).toContain('홑따옴표');
    expect(markdown).toContain('후행 쉼표');
    expect(markdown).toContain('all');
  });
});
