import type { TechStack } from '@/features/widgets/techStack/types/techStack';

export const TECH_STACKS: TechStack[] = [
  // Frontend (Web)
  { id: 'javascript', category: 'Frontend', name: 'JavaScript' },
  { id: 'typescript', category: 'Frontend', name: 'TypeScript' },
  { id: 'html5/css3', category: 'Frontend', name: 'HTML5 / CSS3' },
  { id: 'react', category: 'Frontend', name: 'React' },
  { id: 'nextjs', category: 'Frontend', name: 'Next.js' },
  { id: 'vue', category: 'Frontend', name: 'Vue.js' },
  { id: 'nuxt', category: 'Frontend', name: 'Nuxt' },
  { id: 'svelte', category: 'Frontend', name: 'Svelte' },
  { id: 'sveltekit', category: 'Frontend', name: 'SvelteKit' },
  { id: 'angular', category: 'Frontend', name: 'Angular' },
  { id: 'qwik', category: 'Frontend', name: 'Qwik' },
  { id: 'astro', category: 'Frontend', name: 'Astro' },
  { id: 'remix', category: 'Frontend', name: 'Remix' },
  { id: 'jquery', category: 'Frontend', name: 'JQuery' },
  { id: 'electron', category: 'Frontend', name: 'Electron' },
  { id: 'tauri', category: 'Frontend', name: 'Tauri' },
  { id: 'redux', category: 'Frontend', name: 'Redux / Redux Toolkit' },
  { id: 'recoil', category: 'Frontend', name: 'Recoil' },
  { id: 'zustand', category: 'Frontend', name: 'Zustand' },
  { id: 'jotai', category: 'Frontend', name: 'Jotai' },
  { id: 'mobx', category: 'Frontend', name: 'MobX' },
  { id: 'tanstackquery', category: 'Frontend', name: 'TanStack Query' },
  { id: 'swr', category: 'Frontend', name: 'SWR' },
  { id: 'tailwindcss', category: 'Frontend', name: 'Tailwind CSS' },
  { id: 'styledcomponents', category: 'Frontend', name: 'styled-components' },
  { id: 'emotion', category: 'Frontend', name: 'Emotion' },
  { id: 'sassscss', category: 'Frontend', name: 'Sass/SCSS' },
  { id: 'vanillaextract', category: 'Frontend', name: 'Vanilla Extract' },
  { id: 'bootstrap', category: 'Frontend', name: 'Bootstrap' },
  { id: 'mui', category: 'Frontend', name: 'MUI' },
  { id: 'chakraui', category: 'Frontend', name: 'Chakra UI' },
  { id: 'antdesign', category: 'Frontend', name: 'Ant Design' },
  { id: 'shadcn/ui', category: 'Frontend', name: 'Shadcn/ui' },

  // Mobile
  { id: 'reactnative', category: 'Mobile', name: 'React Native' },
  { id: 'flutter', category: 'Mobile', name: 'Flutter' },
  { id: 'swift/swiftui', category: 'Mobile', name: 'Swift / SwiftUI' },
  {
    id: 'kotlin/jetpackcompose',
    category: 'Mobile',
    name: 'Kotlin / Jetpack Compose',
  },
  { id: 'expo', category: 'Mobile', name: 'Expo' },

  // Backend
  { id: 'nodejs', category: 'Backend', name: 'Node.js' },
  { id: 'java', category: 'Backend', name: 'Java' },
  { id: 'python', category: 'Backend', name: 'Python' },
  { id: 'kotlin', category: 'Backend', name: 'Kotlin' },
  { id: 'go', category: 'Backend', name: 'Go' },
  { id: 'rust', category: 'Backend', name: 'Rust' },
  { id: 'csharp', category: 'Backend', name: 'C#' },
  { id: 'php', category: 'Backend', name: 'PHP' },
  { id: 'ruby', category: 'Backend', name: 'Ruby' },
  { id: 'scala', category: 'Backend', name: 'Scala' },
  { id: 'elixir', category: 'Backend', name: 'Elixir' },
  { id: 'nestjs', category: 'Backend', name: 'NestJS' },
  { id: 'expressjs', category: 'Backend', name: 'Express.js' },
  { id: 'fastify', category: 'Backend', name: 'Fastify' },
  { id: 'springboot', category: 'Backend', name: 'Spring Boot' },
  { id: 'fastapi', category: 'Backend', name: 'FastAPI' },
  { id: 'django', category: 'Backend', name: 'Django' },
  { id: 'flask', category: 'Backend', name: 'Flask' },
  { id: 'gin', category: 'Backend', name: 'Gin' },
  { id: 'rubyonrails', category: 'Backend', name: 'Ruby on Rails' },
  { id: 'laravel', category: 'Backend', name: 'Laravel' },
  { id: 'aspnetcore', category: 'Backend', name: 'ASP.NET Core' },
  { id: 'prisma', category: 'Backend', name: 'Prisma' },
  { id: 'typeorm', category: 'Backend', name: 'TypeORM' },
  { id: 'sequelize', category: 'Backend', name: 'Sequelize' },
  { id: 'drizzleorm', category: 'Backend', name: 'Drizzle ORM' },
  { id: 'jpa/hibernate', category: 'Backend', name: 'JPA / Hibernate' },
  { id: 'mongoose', category: 'Backend', name: 'Mongoose' },
  { id: 'mybatis', category: 'Backend', name: 'MyBatis' },

  // Data
  { id: 'mysql', category: 'Data', name: 'MySQL' },
  { id: 'postgresql', category: 'Data', name: 'PostgreSQL' },
  { id: 'mariadb', category: 'Data', name: 'MariaDB' },
  { id: 'oracle', category: 'Data', name: 'Oracle' },
  { id: 'mssql', category: 'Data', name: 'MSSQL' },
  { id: 'sqlite', category: 'Data', name: 'SQLite' },
  { id: 'mongodb', category: 'Data', name: 'MongoDB' },
  { id: 'redis', category: 'Data', name: 'Redis' },
  { id: 'dynamodb', category: 'Data', name: 'DynamoDB' },
  { id: 'firestore', category: 'Data', name: 'Firestore' },
  { id: 'cassandra', category: 'Data', name: 'Cassandra' },
  { id: 'elasticsearch', category: 'Data', name: 'Elasticsearch' },
  { id: 'firebase', category: 'Data', name: 'Firebase' },
  { id: 'supabase', category: 'Data', name: 'Supabase' },
  { id: 'pocketbase', category: 'Data', name: 'PocketBase' },
  { id: 'appwrite', category: 'Data', name: 'Appwrite' },
  { id: 'kafka', category: 'Data', name: 'Kafka' },
  { id: 'rabbitmq', category: 'Data', name: 'RabbitMQ' },

  // Infrastructure (Cloud, DevOps, CI/CD)
  { id: 'ncp', category: 'Infrastructure', name: 'NCP' },
  { id: 'aws', category: 'Infrastructure', name: 'AWS' },
  { id: 'gcp', category: 'Infrastructure', name: 'GCP' },
  { id: 'azure', category: 'Infrastructure', name: 'Azure' },
  { id: 'vercel', category: 'Infrastructure', name: 'Vercel' },
  { id: 'netlify', category: 'Infrastructure', name: 'Netlify' },
  { id: 'heroku', category: 'Infrastructure', name: 'Heroku' },
  { id: 'railway', category: 'Infrastructure', name: 'Railway' },
  { id: 'flyio', category: 'Infrastructure', name: 'Fly.io' },
  {
    id: 'cloudflareworkers',
    category: 'Infrastructure',
    name: 'Cloudflare Workers',
  },
  { id: 'docker', category: 'Infrastructure', name: 'Docker' },
  { id: 'kubernetes', category: 'Infrastructure', name: 'Kubernetes' },
  { id: 'jenkins', category: 'Infrastructure', name: 'Jenkins' },
  { id: 'githubactions', category: 'Infrastructure', name: 'GitHub Actions' },
  { id: 'gitlabci', category: 'Infrastructure', name: 'GitLab CI' },
  { id: 'terraform', category: 'Infrastructure', name: 'Terraform' },
  { id: 'ansible', category: 'Infrastructure', name: 'Ansible' },
  { id: 'nginx', category: 'Infrastructure', name: 'Nginx' },

  // Collaboration
  { id: 'figma', category: 'Collaboration', name: 'Figma' },
  { id: 'adobexd', category: 'Collaboration', name: 'Adobe XD' },
  { id: 'zeplin', category: 'Collaboration', name: 'Zeplin' },
  { id: 'sketch', category: 'Collaboration', name: 'Sketch' },
  {
    id: 'photoshop/illustrator',
    category: 'Collaboration',
    name: 'Photoshop / Illustrator',
  },
  { id: 'slack', category: 'Collaboration', name: 'Slack' },
  { id: 'discord', category: 'Collaboration', name: 'Discord' },
  { id: 'notion', category: 'Collaboration', name: 'Notion' },
  { id: 'jira', category: 'Collaboration', name: 'Jira' },
  { id: 'trello', category: 'Collaboration', name: 'Trello' },
  { id: 'linear', category: 'Collaboration', name: 'Linear' },
  { id: 'asana', category: 'Collaboration', name: 'Asana' },
  { id: 'confluence', category: 'Collaboration', name: 'Confluence' },
  { id: 'git', category: 'Collaboration', name: 'Git' },
  { id: 'github', category: 'Collaboration', name: 'GitHub' },
  { id: 'gitlab', category: 'Collaboration', name: 'GitLab' },
  { id: 'bitbucket', category: 'Collaboration', name: 'Bitbucket' },
];

// 예외 처리가 필요한 이름들을 매핑(Simple Icons 슬러그 기준)
export const iconMap: Record<string, string> = {
  'React Native': 'react',
  'C#': 'csharp',
  'Express.js': 'express',
  GCP: 'googlecloud',
  NCP: 'naver',
  'Photoshop / Illustrator': 'adobephotoshop',
  'styled-components': 'styledcomponents',
  SvelteKit: 'svelte',
  'TanStack Query': 'tanstack',
  'Shadcn/ui': 'shadcnui',
  'Drizzle ORM': 'drizzle',
  Cassandra: 'apachecassandra',
  'JPA / Hibernate': 'hibernate',
  MyBatis: 'mybatis',
  Kafka: 'kafka',
  'GitLab CI': 'gitlab',
};
