import { LuFileText, LuX, LuCopy, LuCheck } from 'react-icons/lu';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  techStack: Set<string>;
}

function ExportModal({ isOpen, onClose, techStack }: ExportModalProps) {
  const generateMarkdown = () => {
    const techs = Array.from(techStack)
      .map((t) => `| ${t} | vLatest | Selected |`)
      .join('\n');

    return `# 🚀 Project Team Align Report
> Created at: ${new Date().toLocaleString()}


## 2. 🛠 Tech Stack Selection
| Tech Name | Version | Status |
| :--- | :--- | :--- |
${techs.length ? techs : '| None | - | - |'}

---
*Generated by TeamConfig*`;
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-100 flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm">
      <div className="animate-scale-in flex max-h-[85vh] w-full max-w-3xl flex-col rounded-xl border border-gray-700 bg-gray-800 shadow-2xl">
        <div className="flex items-center justify-between rounded-t-xl border-b border-gray-700 bg-gray-900 p-5">
          <div className="flex items-center gap-3">
            <div className="rounded-lg bg-gray-800 p-2">
              <LuFileText className="text-white" size={24} />
            </div>
            <div>
              <h3 className="text-lg font-bold text-white">
                Export to README.md
              </h3>
              <p className="text-xs text-gray-400">
                GitHub 위키나 README에 바로 붙여넣으세요.
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="text-gray-400 transition-colors hover:text-white"
          >
            <LuX size={24} />
          </button>
        </div>

        <div className="group relative flex-1 overflow-auto bg-[#0d1117] p-0">
          <div className="absolute top-4 right-4 z-10 opacity-0 transition-opacity group-hover:opacity-100">
            <button
              onClick={() => navigator.clipboard.writeText(generateMarkdown())}
              className="flex items-center gap-2 rounded border border-gray-600 bg-gray-700 px-3 py-1.5 text-xs text-white shadow-lg hover:bg-gray-600"
            >
              <LuCopy size={12} /> Copy Raw
            </button>
          </div>
          <pre className="p-6 font-mono text-sm leading-relaxed whitespace-pre-wrap text-gray-300 selection:bg-blue-500 selection:text-white">
            {generateMarkdown()}
          </pre>
        </div>

        <div className="flex justify-end gap-3 rounded-b-xl border-t border-gray-700 bg-gray-800 p-4">
          <button
            onClick={onClose}
            className="rounded-lg px-4 py-2 text-sm font-medium text-gray-300 transition-colors hover:bg-gray-700 hover:text-white"
          >
            Cancel
          </button>
          <button
            onClick={() => {
              navigator.clipboard.writeText(generateMarkdown());
              alert('Copied to clipboard!');
            }}
            className="flex items-center gap-2 rounded-lg bg-blue-600 px-5 py-2 text-sm font-bold text-white shadow-lg shadow-blue-500/20 transition-all hover:bg-blue-500"
          >
            <LuCheck size={16} />
            Copy to Clipboard
          </button>
        </div>
      </div>
    </div>
  );
}

export default ExportModal;
