import { Injectable, Inject } from '@nestjs/common';
import type { IWidgetService } from '../widget/widget.interface';
import { WIDGET_SERVICE } from '../widget/widget.interface';
import {
  WidgetType,
  GroundRuleContentDto,
  TechStackContentDto,
  PostItContentDto,
} from '../widget/dto/widget-content.dto';
import { CreateWidgetDto } from '../widget/dto/create-widget.dto';

@Injectable()
export class MarkdownService {
  constructor(
    @Inject(WIDGET_SERVICE) private readonly widgetService: IWidgetService,
  ) {}

  private buildGroundRuleSection(widgets: CreateWidgetDto[]): string[] {
    if (!widgets || widgets.length === 0) return [];

    const lines: string[] = [];
    lines.push('## 1. 📋 Ground Rule');
    lines.push('| Rule | Description |');
    lines.push('| :--- | :--- |');
    widgets.forEach((widget) => {
      const content = widget.data.content as GroundRuleContentDto;
      if (content.rules && content.rules.length > 0) {
        content.rules.forEach((rule) => {
          lines.push(`| ${rule} | - |`);
        });
      }
    });

    lines.push('');
    return lines;
  }

  private buildTechStackSection(widgets: CreateWidgetDto[]): string[] {
    if (!widgets || widgets.length === 0) return [];

    const lines: string[] = [];
    lines.push('## 2. 🛠 Tech Stack Selection');
    lines.push('| Tech Name | Version |');
    lines.push('| :--- | :--- |');

    widgets.forEach((widget) => {
      const content = widget.data.content as TechStackContentDto;
      if (content.selectedItems && content.selectedItems.length > 0) {
        content.selectedItems.forEach((item) => {
          lines.push(`| ${item.name} | vLatest |`);
        });
      }
    });

    lines.push('');
    return lines;
  }

  private buildElseSection(widgets: CreateWidgetDto[]): string[] {
    if (!widgets || widgets.length === 0) return [];

    const lines: string[] = [];

    lines.push('## 3. Else');
    lines.push('---');

    widgets.forEach((widget) => {
      const content = widget.data.content as PostItContentDto;
      if (content.text) {
        lines.push(content.text);
      }
    });

    lines.push('');
    return lines;
  }

  async generateMarkdown(workspaceId: string): Promise<string> {
    const now = new Date();
    const formattedDate = now.toLocaleString('ko-KR', {
      year: 'numeric',
      month: 'numeric',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
      hour12: true,
    });

    const markdownParts: string[] = [];

    markdownParts.push('# 🚀 Project Team Align Report');
    markdownParts.push(`> Created at: ${formattedDate}`);
    markdownParts.push('');

    const allWidgets = await this.widgetService.findAll(workspaceId);

    const groundRuleWidgets = allWidgets.filter(
      (widget) => widget.data.content.widgetType === WidgetType.GROUND_RULE,
    );
    markdownParts.push(...this.buildGroundRuleSection(groundRuleWidgets));

    const techStackWidgets = allWidgets.filter(
      (widget) => widget.data.content.widgetType === WidgetType.TECH_STACK,
    );
    markdownParts.push(...this.buildTechStackSection(techStackWidgets));

    const postItWidgets = allWidgets.filter(
      (widget) => widget.data.content.widgetType === WidgetType.POST_IT,
    );
    markdownParts.push(...this.buildElseSection(postItWidgets));

    if (
      groundRuleWidgets.length === 0 &&
      techStackWidgets.length === 0 &&
      postItWidgets.length === 0
    ) {
      markdownParts.push(
        '아직 적은 내용이 없는 것 같습니다! 위젯에 내용을 추가해보세요! 🚀',
      );
      markdownParts.push('');
    }

    markdownParts.push('*Generated by TeamConfig*');

    return markdownParts.join('\n');
  }
}
