import { Inject, Injectable } from '@nestjs/common';
import { YjsDocReaderService } from '../collaboration/yjs-doc-reader.service';
import { ISectionBuilder, SECTION_BUILDERS } from './builders';

@Injectable()
export class MarkdownService {
  constructor(
    private readonly yjsDocReader: YjsDocReaderService,
    @Inject(SECTION_BUILDERS)
    private readonly builders: ISectionBuilder[],
  ) {}

  /**
   * 헤더 섹션 생성 (문서 생성 일시)
   */
  private buildHeader(): string[] {
    const now = new Date();
    const formattedDate = now.toLocaleString('ko-KR', {
      year: 'numeric',
      month: 'numeric',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
      hour12: true,
    });

    return [`> **문서 생성 일시**: ${formattedDate}`, ''];
  }

  /**
   * 빈 내용일 때 표시할 메시지
   */
  private buildEmptyMessage(): string[] {
    return [
      '### 🚀 아직 작성된 내용이 없습니다.',
      '위젯을 추가하여 팀의 규칙을 정의해보세요!',
      '',
    ];
  }

  /**
   * 푸터 섹션 생성
   */
  private buildFooter(): string[] {
    return ['*Generated by team.config*'];
  }

  /**
   * 워크스페이스의 모든 위젯을 마크다운으로 변환
   */
  generateMarkdown(workspaceId: string): string {
    const allWidgets = this.yjsDocReader.getWidgets(workspaceId);
    const markdownParts: string[] = [...this.buildHeader()];

    let hasContent = false;

    for (const builder of this.builders) {
      const widgets = allWidgets.filter((w) => w.type === builder.widgetType);
      if (widgets.length > 0) {
        hasContent = true;
        markdownParts.push(...builder.build(widgets));
      }
    }

    if (!hasContent) {
      markdownParts.push(...this.buildEmptyMessage());
    }

    markdownParts.push(...this.buildFooter());

    return markdownParts.join('\n');
  }
}
