import { Injectable, Inject } from '@nestjs/common';
import type { IWidgetService } from '../widget/widget.interface';
import { WIDGET_SERVICE } from '../widget/widget.interface';
import {
  WidgetType,
  GroundRuleContentDto,
  TechStackContentDto,
} from '../widget/dto/widget-content.dto';
import { CreateWidgetDto } from '../widget/dto/create-widget.dto';

@Injectable()
export class MarkdownService {
  constructor(
    @Inject(WIDGET_SERVICE) private readonly widgetService: IWidgetService,
  ) {}

  private buildGroundRuleSection(widget: CreateWidgetDto | null): string[] {
    if (!widget) return [];

    const lines: string[] = [];
    const content = widget.data.content as GroundRuleContentDto;

    lines.push('## 1. 📋 Ground Rule');
    lines.push('| Ground Rule| Value| ');
    lines.push('| :--- | :--- | ');

    if (content.rules && content.rules.length > 0) {
      content.rules.forEach((rule) => {
        lines.push(`| ${rule} | - |`);
      });
    }

    lines.push('');
    return lines;
  }

  private buildTechStackSection(widget: CreateWidgetDto | null): string[] {
    if (!widget) return [];

    const lines: string[] = [];
    const content = widget.data.content as TechStackContentDto;

    lines.push('## 2. 🛠 Tech Stack Selection');
    lines.push('| Tech Name | Version |');
    lines.push('| :--- | :--- |');

    if (content.selectedItems && content.selectedItems.length > 0) {
      content.selectedItems.forEach((item) => {
        lines.push(`| ${item} | vLatest |`);
      });
    } else {
      lines.push('| - | - |');
    }

    lines.push('');
    return lines;
  }

  private buildElseSection(widget: CreateWidgetDto | null): string[] {
    const lines: string[] = [];

    lines.push('## 3. Else');
    lines.push('---');

    if (widget) {
      const content = widget.data.content as { text?: string };
      if (content.text) {
        lines.push(content.text);
      }
    }

    lines.push('');
    return lines;
  }

  async generateMarkdown(workspaceId: string): Promise<string> {
    const now = new Date();
    const formattedDate = now.toLocaleString('ko-KR', {
      year: 'numeric',
      month: 'numeric',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
      hour12: true,
    });

    const markdownParts: string[] = [];

    markdownParts.push('# 🚀 Project Team Align Report');
    markdownParts.push(`> Created at: ${formattedDate}`);
    markdownParts.push('');

    const groundRuleWidget = await this.widgetService.findOneByWidgetType(
      workspaceId,
      WidgetType.GROUND_RULE,
    );
    markdownParts.push(...this.buildGroundRuleSection(groundRuleWidget));

    const techStackWidget = await this.widgetService.findOneByWidgetType(
      workspaceId,
      WidgetType.TECH_STACK,
    );
    markdownParts.push(...this.buildTechStackSection(techStackWidget));

    const postItWidget = await this.widgetService.findOneByWidgetType(
      workspaceId,
      WidgetType.POST_IT,
    );

    markdownParts.push(...this.buildElseSection(postItWidget));

    markdownParts.push('*Generated by TeamConfig*');

    return markdownParts.join('\n');
  }
}
